###服务启动端口号
server:
  port: 9000
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-oracle-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka,http://peer2:8001/eureka,http://peer3:8002/eureka

    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true
